<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8rEnTr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8rEnTr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR8rEnTr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR8rEnTr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR8rEnTr\App_KernelDevDebugContainer([
    'container.build_hash' => 'R8rEnTr',
    'container.build_id' => '17640db1',
    'container.build_time' => 1649685319,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8rEnTr');
