<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Tx283Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Tx283Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8Tx283Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8Tx283Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8Tx283Z\App_KernelDevDebugContainer([
    'container.build_hash' => '8Tx283Z',
    'container.build_id' => 'a97a35a9',
    'container.build_time' => 1650489547,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Tx283Z');
